server:
  port: 3000

  spring:
    #데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: PROJECT
    password: _aA123456


  #로거 설정
  logging:
    level:
      org:
        springframework:
          jdbc: trace
